import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/top-nav";
import Nav from "@/components/nav";
import Provider from "@/components/Provider";
import Footer from "@/components/footer";
import StoreProvider from "@/components/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommmerce Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <StoreProvider>
            <TopNav />
            <Nav />

            <Provider>{children}</Provider>
            <Footer />
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
